name: Pull requests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.3 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        run: composer install
      - name: Run PHP Coding Standards Fixer
        run: ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix -v --dry-run
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G
      - name: Run tests
        run: ./vendor/bin/phpunit --configuration ./phpunit.xml --coverage-cobertura=cobertura.xml
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'
